# Generated by Django 3.2.5 on 2022-12-01 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_site', '0006_auto_20221130_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bids',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 22, 32, 22, 410562)),
        ),
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.ImageField(default='/frontend/src/images/ItemNoImage.jpg', upload_to='./auction_site/frontend/src/images/ItemImages'),
        ),
        migrations.AlterField(
            model_name='replies',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 22, 32, 22, 410562)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 22, 32, 22, 410562)),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='/frontend/src/images/default_user.png', upload_to='./auction_site/frontend/src/images/UserImages'),
        ),
    ]
