# Generated by Django 4.1.2 on 2022-12-08 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_site', '0007_auto_20221201_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 19, 58, 45, 2883)),
        ),
        migrations.AlterField(
            model_name='products',
            name='starting_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='replies',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 19, 58, 45, 1882)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 19, 58, 45, 1882)),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True),
        ),
    ]
