# Generated by Django 3.2.5 on 2022-12-10 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_site', '0008_alter_bids_date_posted_alter_products_starting_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 15, 41, 20, 353490)),
        ),
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='replies',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 15, 41, 20, 353490)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 15, 41, 20, 353490)),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
