# Generated by Django 3.2.5 on 2022-12-14 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_site', '0009_auto_20221210_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 23, 52, 15, 906010)),
        ),
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.ImageField(blank=True, default='./ItemNoImage.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='replies',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 23, 52, 15, 906010)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 23, 52, 15, 905009)),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='./default_user.png', null=True, upload_to=''),
        ),
    ]
